[project]
name = "carbon_frappe"
authors = [
    { name = "Avunu LLC", email = "mail@avu.nu" },
]
description = "Carbon Design System theme for Frappe"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = []

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]
