#!/usr/bin/env node
/**
 * Dev-time codegen: vendor IBM Plex woff2 subsets from @ibm/plex-sans /
 * @ibm/plex-mono into carbon_frappe/public/fonts (committed, served at
 * /assets/carbon_frappe/fonts/) and generate the @font-face partial at
 * carbon_frappe/public/scss/generated/_fonts.scss from the packages' own
 * split CSS (which carries the per-subset unicode-range declarations).
 *
 * Run via `npm run codegen` after bumping @ibm/plex-* versions.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fontsOut = path.join(appRoot, "carbon_frappe", "public", "fonts");
const scssOut = path.join(appRoot, "carbon_frappe", "public", "scss", "generated");

// face css basenames in fonts/split/woff2/ of each package
const FACES = {
	"plex-sans": [
		"IBMPlexSans-Light", // 300
		"IBMPlexSans-Regular", // 400
		"IBMPlexSans-Italic", // 400 italic
		"IBMPlexSans-Medium", // 500
		"IBMPlexSans-SemiBold", // 600
	],
	"plex-mono": [
		"IBMPlexMono-Regular", // 400
		"IBMPlexMono-SemiBold", // 600
	],
};

fs.mkdirSync(fontsOut, { recursive: true });
fs.mkdirSync(scssOut, { recursive: true });

let scss = `// GENERATED by scripts/sync-fonts.mjs — DO NOT EDIT.
// IBM Plex @font-face rules (split unicode-range subsets), self-hosted at
// /assets/carbon_frappe/fonts/. Source: @ibm/plex-sans, @ibm/plex-mono.
`;

let copied = 0;
for (const [pkg, faces] of Object.entries(FACES)) {
	const splitDir = path.join(appRoot, "node_modules", "@ibm", pkg, "fonts", "split", "woff2");
	for (const face of faces) {
		const css = fs.readFileSync(path.join(splitDir, `${face}.css`), "utf-8");
		scss +=
			"\n" +
			css
				// self-hosted absolute URLs (public/ is symlinked to /assets/carbon_frappe/)
				.replaceAll(/url\("([^"]+)"\)/g, 'url("/assets/carbon_frappe/fonts/$1")')
				// the split css ships without font-display
				.replaceAll(/(font-weight:\s*\d+;)/g, "$1\n\tfont-display: swap;");
		for (const m of css.matchAll(/url\("([^"]+\.woff2)"\)/g)) {
			fs.copyFileSync(path.join(splitDir, m[1]), path.join(fontsOut, m[1]));
			copied++;
		}
	}
	// license alongside the vendored files
	fs.copyFileSync(
		path.join(appRoot, "node_modules", "@ibm", pkg, "LICENSE.txt"),
		path.join(fontsOut, `LICENSE-${pkg}.txt`)
	);
}

fs.writeFileSync(path.join(scssOut, "_fonts.scss"), scss);
console.log(`[sync-fonts] copied ${copied} woff2 files, wrote generated/_fonts.scss`);
