import { after, describe, it } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {
	auditLegacyEmitters,
	diffGeneratedFile,
	findLegacyClassNames,
	findSpriteIds,
	findSpriteReferences,
	legacyEmitterFindings,
	parseGlyphModule,
	pinnedFrappeApps,
	scanLegacyEmitters,
	type LegacyScan,
} from "../../scripts/lib/audit-icons.ts";

describe("findLegacyClassNames", () => {
	it("finds the class however the markup spells the element", () => {
		const text = `
			' <i class="fa fa-lock text-warning"></i>'
			$btn.html(\`<i class="fa fa-spinner fa-spin"></i>\`);
			"icon": "octicon octicon-file-directory",
			<span class="fa-fixed-width fa fa-user"></span>
		`;
		assert.deepEqual([...findLegacyClassNames(text)].sort(), [
			"fa-fixed-width",
			"fa-lock",
			"fa-spin",
			"fa-spinner",
			"fa-user",
			"octicon-file-directory",
		]);
	});
	it("keeps multi-word names whole", () => {
		assert.deepEqual([...findLegacyClassNames("fa fa-angle-double-right")], ["fa-angle-double-right"]);
	});
	it("does not read a locale code or an unrelated word as an icon", () => {
		assert.equal(findLegacyClassNames("lang = 'fa-IR'; const sofa = 1; fax-number").size, 0);
	});
});

describe("findSpriteReferences", () => {
	it("reads href fragments and frappe.utils.icon calls, normalising to the sprite's ids", () => {
		const text = `
			<svg><use href="#icon-heart"></use></svg>
			frappe.utils.icon("square-pen", "sm")
			utils?.icon('es-line-search')
		`;
		assert.deepEqual([...findSpriteReferences(text)].sort(), [
			"es-line-search",
			"icon-heart",
			"icon-square-pen",
		]);
	});
	it("ignores a dynamic name rather than guessing one", () => {
		assert.equal(findSpriteReferences("frappe.utils.icon(name, size)").size, 0);
	});
});

describe("findSpriteIds", () => {
	it("lists every <symbol> id in a sprite sheet", () => {
		const svg = `<svg><symbol viewBox="0 0 16 16" id="icon-up"><path/></symbol>
			<symbol id="es-line-x" viewBox="0 0 1 1"/></svg>`;
		assert.deepEqual([...findSpriteIds(svg)].sort(), ["es-line-x", "icon-up"]);
	});
});

describe("parseGlyphModule and diffGeneratedFile", () => {
	const header = "// GENERATED by x — DO NOT EDIT.\n// @carbon/icons 1.0.0 glyphs\n";
	const generated = `${header}/** up 16 — a thing. */\nexport const up16: string = ${JSON.stringify('<svg class="a"><path d="M1"/></svg>')};\n`;
	// what the formatter makes of it: rewrapped, and single-quoted to spare the escapes
	const formatted = `${header}/** up 16 — a thing. */\nexport const up16: string =\n\t'<svg class="a"><path d="M1"/></svg>';\n`;

	it("reads the same module through the formatter's rewrapping and quote swap", () => {
		assert.deepEqual(parseGlyphModule(formatted), parseGlyphModule(generated));
		assert.deepEqual(parseGlyphModule(generated).exports, [
			{ doc: "up 16 — a thing.", name: "up16", value: '<svg class="a"><path d="M1"/></svg>' },
		]);
		assert.deepEqual(diffGeneratedFile("x.ts", generated, formatted), []);
	});
	it("catches changed markup, a changed version, and a dropped or extra export", () => {
		assert.deepEqual(diffGeneratedFile("x.ts", generated, formatted.replace("M1", "M2")), [
			"up16's markup differs",
		]);
		assert.match(diffGeneratedFile("x.ts", generated, formatted.replace("1.0.0", "1.0.1")).join(), /header/);
		assert.deepEqual(diffGeneratedFile("x.ts", generated, header), ["up16 is missing"]);
		assert.deepEqual(diffGeneratedFile("x.ts", header, formatted), ["up16 is no longer listed"]);
	});
	it("catches code the generator never writes, after or between the entries", () => {
		for (const extra of ['export const evil16 = "<svg></svg>";', "export function boom() { return 1; }"]) {
			assert.match(
				diffGeneratedFile("x.ts", generated, `${formatted}${extra}\n`).join(),
				/text the generator/,
			);
		}
		const two = `${generated}/** down 16 — another. */\nexport const down16: string = "<svg/>";\n`;
		const wedged = two.replace("/** down", "export function boom() {}\n/** down");
		assert.deepEqual(parseGlyphModule(wedged).exports, parseGlyphModule(two).exports);
		assert.match(diffGeneratedFile("x.ts", two, wedged).join(), /text the generator.*boom/);
	});
	it("compares a stylesheet whitespace aside, and nothing else aside", () => {
		assert.deepEqual(diffGeneratedFile("x.scss", ".a {\n\tb: c;\n}\n", ".a {\n  b: c;\n}"), []);
		assert.deepEqual(diffGeneratedFile("x.scss", ".a {\n\tb: c;\n}\n", ".a {\n\tb: d;\n}\n"), [
			"its rules differ",
		]);
	});
});

describe("legacyEmitterFindings", () => {
	const answers = new Map<string, readonly string[]>([
		["fa-lock", ["frappe"]],
		["fa-font", ["print_designer"]],
		["fa-gone", ["frappe"]],
	]);
	const scan = (emitted: Record<string, Record<string, string>>, scanned: string[]): LegacyScan => ({
		scanned,
		emitted: new Map(Object.entries(emitted).map(([k, v]) => [k, new Map(Object.entries(v))])),
	});

	it("is clean when every emitter is answered and every answer has its emitters", () => {
		const s = scan(
			{ "fa-lock": { frappe: "a.js" }, "fa-gone": { frappe: "b.py" }, "fa-spin": { frappe: "c.vue" } },
			["frappe"],
		);
		assert.deepEqual(legacyEmitterFindings(s, answers, ["fa-spin"]), []);
	});
	it("flags a class with no answer", () => {
		const s = scan(
			{ "fa-lock": { frappe: "a" }, "fa-gone": { frappe: "b" }, "fa-new": { erpnext: "x.js" } },
			["frappe", "erpnext"],
		);
		const findings = legacyEmitterFindings(s, answers, []);
		assert.equal(findings.length, 1);
		assert.match(findings[0] ?? "", /^x\.js emits \.fa-new, which frappe no longer styles/);
	});
	it("flags an emitter its entry does not name, and an entry nothing emits any more", () => {
		const s = scan({ "fa-lock": { frappe: "a", hrms: "h.html" } }, ["frappe", "hrms"]);
		const findings = legacyEmitterFindings(s, answers, []);
		assert.equal(findings.length, 2);
		assert.match(findings[0] ?? "", /h\.html emits \.fa-lock, but .* add hrms/);
		assert.match(findings[1] ?? "", /says frappe emits \.fa-gone, but nothing in frappe does/);
	});
	it("neither confirms nor refutes an app it did not scan", () => {
		// fa-font's print_designer was not scanned: no finding either way
		const s = scan({ "fa-lock": { frappe: "a" }, "fa-gone": { frappe: "b" } }, ["frappe"]);
		assert.deepEqual(legacyEmitterFindings(s, answers, []), []);
	});
});

describe("scanLegacyEmitters and auditLegacyEmitters on a bench layout", () => {
	const root = fs.mkdtempSync(path.join(os.tmpdir(), "carbon-audit-icons-"));
	after(() => fs.rmSync(root, { recursive: true, force: true }));
	const put = (rel: string, text: string): void => {
		fs.mkdirSync(path.dirname(path.join(root, rel)), { recursive: true });
		fs.writeFileSync(path.join(root, rel), text);
	};
	put("apps/frappe/frappe/public/js/lib/locate/L.Control.Locate.js", "icon: 'fa fa-map-marker'");
	put("apps/frappe/frappe/core/file.py", '<i class="fa fa-lock"></i>');
	put("apps/frappe/frappe/public/node_modules/pkg/x.js", "fa-from-node-modules");
	put("apps/frappe/frappe/public/dist/js/x.js", "fa-from-dist");
	put("apps/frappe/frappe/public/js/vendor.min.js", "fa-from-min");
	put("apps/frappe/frappe/public/scss/report.scss", ".fa-from-stylesheet {}");
	put("apps/carbon_frappe/carbon_frappe/public/js/x.ts", "fa-from-the-theme");
	put("apps/hrms/hrms/templates/node_card.html", "fa fa-level-down");
	put("apps/not_an_app/README.md", "fa-ignored");
	const apps = path.join(root, "apps");

	it("reads `lib` directories, and skips node_modules, dist, minified files and stylesheets", () => {
		const s = scanLegacyEmitters([{ name: "frappe", root: path.join(apps, "frappe") }], apps);
		assert.deepEqual(s.scanned, ["frappe"]);
		assert.deepEqual([...s.emitted.keys()].sort(), ["fa-lock", "fa-map-marker"]);
		assert.equal(
			s.emitted.get("fa-map-marker")?.get("frappe"),
			path.join("frappe", "frappe", "public", "js", "lib", "locate", "L.Control.Locate.js"),
		);
	});
	it("scans every app next to frappe but this one, says which, and fails on a pinned app that is absent", () => {
		const warnings: string[] = [];
		const logs: string[] = [];
		auditLegacyEmitters(
			path.join(apps, "frappe"),
			["erpnext", "frappe", "hrms"],
			(m) => warnings.push(m),
			(m) => logs.push(m),
		);
		assert.match(logs.join("\n"), /check 9 scanned frappe, hrms;/);
		assert.ok(warnings.some((w) => /cannot read erpnext, which flake\.lock pins/.test(w)));
		assert.ok(!warnings.some((w) => /fa-from-the-theme|fa-ignored/.test(w)));
	});
	it("lists an absent app as unverified, not as a finding, when no pinned apps are required (warn-only)", () => {
		const warnings: string[] = [];
		const logs: string[] = [];
		auditLegacyEmitters(
			path.join(apps, "frappe"),
			[],
			(m) => warnings.push(m),
			(m) => logs.push(m),
		);
		assert.ok(!warnings.some((w) => /cannot read/.test(w)));
		assert.match(logs.join("\n"), /unverified: .*\berpnext\b/);
	});
	it("says so, rather than returning silently, when FRAPPE_PATH is not an apps/frappe checkout", () => {
		fs.cpSync(path.join(apps, "frappe"), path.join(root, "frappe-v16"), { recursive: true });
		const warnings: string[] = [];
		const logs: string[] = [];
		auditLegacyEmitters(
			path.join(root, "frappe-v16"),
			["frappe", "hrms"],
			(m) => warnings.push(m),
			(m) => logs.push(m),
		);
		assert.match(logs.join("\n"), /not an apps\/frappe checkout/);
		assert.match(logs.join("\n"), /check 9 scanned frappe(;|$)/m);
		assert.ok(warnings.some((w) => /cannot read hrms/.test(w)));
	});
});

describe("pinnedFrappeApps", () => {
	it("lists the frappe-owned inputs flake.lock pins", () => {
		const lock = {
			nodes: {
				erpnext: { locked: { owner: "frappe", repo: "erpnext", type: "github" } },
				frappe: { locked: { owner: "frappe", repo: "frappe", type: "github" } },
				"frappe-nix": { locked: { owner: "Avunu", repo: "frappe-nix", type: "github" } },
				root: { inputs: {} },
			},
		};
		assert.deepEqual(pinnedFrappeApps(lock), ["erpnext", "frappe"]);
		assert.deepEqual(pinnedFrappeApps(null), []);
	});
	it("reads this repo's flake.lock as frappe, erpnext and hrms", () => {
		const lock: unknown = JSON.parse(
			fs.readFileSync(path.resolve(import.meta.dirname, "..", "..", "flake.lock"), "utf-8"),
		);
		assert.deepEqual(pinnedFrappeApps(lock), ["erpnext", "frappe", "hrms"]);
	});
});
