import { describe, it } from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import { CARBON } from "../../carbon_frappe/public/js/tables/engine/classes.ts";
import { auditGeneratedIcons } from "../../scripts/lib/audit-icons.ts";
import {
	CHROME_GLYPHS,
	LEGACY_GLYPHS,
	LEGACY_UNMAPPED,
	SHELL_GLYPHS,
} from "../../scripts/lib/icon-manifest.ts";
import { glyphModule, legacyClassName, legacyStylesheet, svgDataUri } from "../../scripts/lib/icons.ts";

const appRoot = path.resolve(import.meta.dirname, "..", "..");

describe("svgDataUri", () => {
	it("escapes what would end the URL or the document, and swaps to single quotes", () => {
		const uri = svgDataUri('<svg xmlns="http://www.w3.org/2000/svg"><path fill="#fff" d="M1 1"/></svg>');
		assert.equal(
			uri,
			"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3Cpath fill='%23fff' d='M1 1'/%3E%3C/svg%3E",
		);
		assert.doesNotMatch(uri, /[<>"#]/);
	});
	it("escapes a literal percent sign before it escapes anything else", () => {
		assert.equal(svgDataUri("<svg>50%</svg>"), "data:image/svg+xml,%3Csvg%3E50%25%3C/svg%3E");
	});
	it("refuses markup the quote swap would corrupt", () => {
		assert.throws(() => svgDataUri(`<svg a="it's"/>`), /single quote/);
		assert.throws(() => svgDataUri("<svg>\n</svg>"), /newline/);
	});
});

describe("legacyStylesheet", () => {
	const glyphs = [
		{ family: "fa", name: "lock", icon: "locked", emitters: "x" },
		{ family: "octicon", name: "file-directory", icon: "folder", emitters: "y" },
	] as const;
	const css = legacyStylesheet({
		generator: "scripts/generate-icons.ts",
		version: "9.9.9",
		glyphs,
		render: (g) => `<svg xmlns="http://www.w3.org/2000/svg"><title>${g.icon}</title></svg>`,
	});

	it("gives the shared box only to classes that have a mask, so an unmapped class draws nothing", () => {
		assert.match(css, /\.fa-lock,\n\.octicon-file-directory \{\n\tdisplay: inline-block;/);
		assert.doesNotMatch(css, /^\.fa \{|^\.octicon \{|^\.fa,/m);
	});
	it("sets one mask per class from the rendered glyph", () => {
		assert.match(css, /\.fa-lock \{\n\t\/\/ locked\n\t--cf-legacy-icon: url\("data:image\/svg\+xml,%3Csvg /);
		assert.match(css, /\.octicon-file-directory \{\n\t\/\/ folder\n/);
	});
	it("states which @carbon/icons it was drawn from", () => {
		assert.match(css, /@carbon\/icons 9\.9\.9 glyphs/);
	});
	it("implements the modifiers the bridged classes are used with", () => {
		assert.match(css, /\.fa-fw,\n\.fa-fixed-width \{/);
		assert.match(css, /\.fa-spin \{\n\tanimation: cf-legacy-icon-spin/);
	});
});

describe("glyphModule", () => {
	it("emits one documented, string-annotated export per glyph", () => {
		const text = glyphModule({
			generator: "scripts/generate-icons.ts",
			version: "9.9.9",
			summary: "a test inlines",
			glyphs: [{ exportName: "x16", icon: "x", size: 16, role: "a thing" }],
			render: () => "<svg/>",
		});
		assert.match(text, /^\/\/ GENERATED by scripts\/generate-icons\.ts — DO NOT EDIT\./);
		assert.match(text, /\/\*\* x 16 — a thing\. \*\/\nexport const x16: string = "<svg\/>";/);
	});
});

describe("icon manifest", () => {
	it("has no duplicate export names across the generated modules", () => {
		const names = [...SHELL_GLYPHS, ...CHROME_GLYPHS].map((g) => g.exportName);
		assert.equal(new Set(names).size, names.length);
	});
	it("has no duplicate legacy classes, and never both bridges and skips one", () => {
		const classes = LEGACY_GLYPHS.map(legacyClassName);
		assert.equal(new Set(classes).size, classes.length);
		for (const name of classes) assert.ok(!(name in LEGACY_UNMAPPED), `${name} is bridged AND skipped`);
	});
	it("gives every skipped class a reason", () => {
		for (const [name, why] of Object.entries(LEGACY_UNMAPPED)) {
			assert.ok(why.length > 10, `${name} needs a reason`);
		}
	});
	it("pre-classes the expand chevron with the class the engine's CSS targets", () => {
		const chevron = CHROME_GLYPHS.find((g) => g.exportName === "chevronRight16");
		assert.equal(chevron?.attrs?.["class"], CARBON.expandSvg);
	});
});

describe("committed generated icons", () => {
	it("match the manifest and the installed @carbon/icons (run `yarn codegen` if this fails)", () => {
		const findings: string[] = [];
		auditGeneratedIcons(appRoot, (message) => findings.push(message));
		assert.deepEqual(findings, []);
	});
});
