import { describe, it } from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import { CARBON } from "../../carbon_frappe/public/js/tables/engine/classes.ts";
import { auditGeneratedIcons } from "../../scripts/lib/audit-icons.ts";
import {
	CHROME_GLYPHS,
	LEGACY_GLYPHS,
	LEGACY_MODIFIERS,
	LEGACY_UNMAPPED,
	SHELL_GLYPHS,
} from "../../scripts/lib/icon-manifest.ts";
import { glyphModule, legacyClassName, legacyStylesheet, svgDataUri } from "../../scripts/lib/icons.ts";

const appRoot = path.resolve(import.meta.dirname, "..", "..");

describe("svgDataUri", () => {
	it("escapes what would end the URL or the document, and swaps to single quotes", () => {
		const uri = svgDataUri('<svg xmlns="http://www.w3.org/2000/svg"><path fill="#fff" d="M1 1"/></svg>');
		assert.equal(
			uri,
			"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3Cpath fill='%23fff' d='M1 1'/%3E%3C/svg%3E",
		);
		assert.doesNotMatch(uri, /[<>"#]/);
	});
	it("escapes a literal percent sign before it escapes anything else", () => {
		assert.equal(svgDataUri("<svg>50%</svg>"), "data:image/svg+xml,%3Csvg%3E50%25%3C/svg%3E");
	});
	it("refuses markup the quote swap would corrupt", () => {
		assert.throws(() => svgDataUri(`<svg a="it's"/>`), /single quote/);
		assert.throws(() => svgDataUri("<svg>\n</svg>"), /newline/);
	});
});

describe("legacyStylesheet", () => {
	const glyphs = [
		{ family: "fa", name: "lock", icon: "locked", apps: ["frappe"], emitters: "x" },
		{ family: "octicon", name: "file-directory", icon: "folder", apps: ["wiki"], emitters: "y" },
	] as const;
	const css = legacyStylesheet({
		generator: "scripts/generate-icons.ts",
		version: "9.9.9",
		glyphs,
		render: (g) => `<svg xmlns="http://www.w3.org/2000/svg"><title>${g.icon}</title></svg>`,
	});

	it("gives the shared box only to classes that have a mask, so an unmapped class draws nothing", () => {
		assert.match(
			css,
			/\.fa-lock::before,\n\.octicon-file-directory::before \{\n\tcontent: "";\n\tdisplay: inline-block;/,
		);
		assert.doesNotMatch(css, /^\.fa \{|^\.octicon \{|^\.fa,|^\.fa::before/m);
	});
	it("paints in ::before, so the element's own display and padding cannot collapse the glyph", () => {
		// print_designer toggles `.icon-show { display: unset }` (inline: no box to
		// paint) and pads `.fa-font` as spacing beside its label.
		const rule = /\.fa-lock::before,[^{]*\{([^}]*)\}/.exec(css)?.[1] ?? "";
		assert.match(rule, /inline-size: 1em;/);
		assert.match(rule, /box-sizing: content-box;/);
		assert.match(rule, /mask: var\(--cf-legacy-icon\)/);
		// the element itself only carries the glyph, as an inherited custom property
		const host = /\n\.fa-lock \{([^}]*)\}/.exec(css)?.[1] ?? "";
		assert.deepEqual(
			host
				.split("\n")
				.map((l) => l.trim())
				.filter((l) => l && !l.startsWith("//"))
				.map((l) => l.split(":")[0]),
			["--cf-legacy-icon"],
		);
	});
	it("sets one mask per class from the rendered glyph", () => {
		assert.match(css, /\.fa-lock \{\n\t\/\/ locked\n\t--cf-legacy-icon: url\("data:image\/svg\+xml,%3Csvg /);
		assert.match(css, /\.octicon-file-directory \{\n\t\/\/ folder\n/);
	});
	it("states which @carbon/icons it was drawn from", () => {
		assert.match(css, /@carbon\/icons 9\.9\.9 glyphs/);
	});
	it("implements every modifier the manifest leaves to it, on the glyph", () => {
		assert.match(css, /\.fa-fw::before,\n\.fa-fixed-width::before \{/);
		// an inline <i> ignores transform, so the spin must turn the pseudo-element
		assert.match(css, /\.fa-spin::before \{\n\tanimation: cf-legacy-icon-spin/);
		for (const modifier of LEGACY_MODIFIERS) assert.match(css, new RegExp(`\\.${modifier}::before[,\\s{]`));
	});
});

describe("glyphModule", () => {
	it("emits one documented, string-annotated export per glyph", () => {
		const text = glyphModule({
			generator: "scripts/generate-icons.ts",
			version: "9.9.9",
			summary: "a test inlines",
			glyphs: [{ exportName: "x16", icon: "x", size: 16, role: "a thing" }],
			render: () => "<svg/>",
		});
		assert.match(text, /^\/\/ GENERATED by scripts\/generate-icons\.ts — DO NOT EDIT\./);
		assert.match(text, /\/\*\* x 16 — a thing\. \*\/\nexport const x16: string = "<svg\/>";/);
	});
});

describe("icon manifest", () => {
	it("has no duplicate export names across the generated modules", () => {
		const names = [...SHELL_GLYPHS, ...CHROME_GLYPHS].map((g) => g.exportName);
		assert.equal(new Set(names).size, names.length);
	});
	it("has no duplicate legacy classes, and never both bridges and skips one", () => {
		const classes = LEGACY_GLYPHS.map(legacyClassName);
		assert.equal(new Set(classes).size, classes.length);
		for (const name of classes) assert.ok(!(name in LEGACY_UNMAPPED), `${name} is bridged AND skipped`);
	});
	it("gives every skipped class a reason, and every entry the apps that emit it", () => {
		for (const [name, { apps, reason }] of Object.entries(LEGACY_UNMAPPED)) {
			assert.ok(reason.length > 10, `${name} needs a reason`);
			assert.ok(apps.length > 0, `${name} needs its emitting apps`);
		}
		for (const glyph of LEGACY_GLYPHS)
			assert.ok(glyph.apps.length > 0, `${legacyClassName(glyph)} needs apps`);
	});
	it("leaves the modifiers to the stylesheet, not to either table", () => {
		const bridged = new Set(LEGACY_GLYPHS.map(legacyClassName));
		for (const modifier of LEGACY_MODIFIERS) {
			assert.ok(!bridged.has(modifier) && !(modifier in LEGACY_UNMAPPED), `${modifier} is listed twice`);
		}
	});
	it("pre-classes the expand chevron with the class the engine's CSS targets", () => {
		const chevron = CHROME_GLYPHS.find((g) => g.exportName === "chevronRight16");
		assert.equal(chevron?.attrs?.["class"], CARBON.expandSvg);
	});
});

describe("committed generated icons", () => {
	// needs @carbon/icons installed: it regenerates the files and compares them
	it("are what the manifest and the installed @carbon/icons generate (run `yarn codegen` if this fails)", () => {
		const findings: string[] = [];
		auditGeneratedIcons(appRoot, (message) => findings.push(message));
		assert.deepEqual(findings, []);
	});
});
